name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  phpstan:
    name: PHPStan

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: PHPStan
        run: vendor/bin/phpstan analyse app -l max
